module.exports = {
    CU_USERNAME_INVALID: 'ERROR_CUSTOMER_001',
    CU_EMAIL_INVALID: 'ERROR_CUSTOMER_002',
    CU_TEL_INVALID: 'ERROR_CUSTOMER_003',
    CU_PASSWORD_INVALID: 'ERROR_CUSTOMER_004',
    CU_ADRESS_INVALID: 'ERROR_CUSTOMER_005',
    CU_ALREADY_EXISTS: 'ERROR_CUSTOMER_006',
    NOT_CUSTOMER: 'ERROR_CUSTOMER_007',
    CU_PASSWORD_NOT_RESET: 'ERROR_CUSTOMER_008',
    CU_MISSING_FIELDS: 'ERROR_CUSTOMER_009',
    CU_INVALID_CREDENTIALS: 'ERROR_CUSTOMER_010',
    CU_DENIED_CREDENTIALS: 'ERROR_CUSTOMER_011'
    // ... autres codes d'erreur liés aux utilisateurs
};