module.exports = {
    SL_USERNAME_INVALID: 'ERROR_SELLER_001',
    SL_EMAIL_INVALID: 'ERROR_SELLER_002',
    SL_TEL_INVALID: 'ERROR_SELLER_003',
    SL_PASSWORD_INVALID: 'ERROR_SELLER_004',
    SL_ADRESS_INVALID: 'ERROR_SELLER_005',
    SL_ALREADY_EXISTS: 'ERROR_SELLER_006',
    NOT_SELLER: 'ERROR_SELLER_007',
    SL_PASSWORD_NOT_RESET: 'ERROR_SELLER_008',
    SL_MISSING_FIELDS: 'ERROR_SELLER_009',
    SL_INVALID_CREDENTIALS: 'ERROR_SELLER_010',
    SL_DENIED_CREDENTIALS: 'ERROR_SELLER_011',
    SL_COMPANY_INVALID: 'ERROR_SELLER_012',
    SL_CI_INVALID: 'ERROR_SELLER_013',
    SL_CATEGORY_INVALID: 'ERROR_SELLER_013',
    SL_HOURSTART_INVALID: 'ERROR_SELLER_014',
    SL_HOUREND_INVALID: 'ERROR_SELLER_015',
    SL_HOURENDSUP_INVALID: 'ERROR_SELLER_016',
    SL_NOT_AUTHENTICATED: 'ERROR_SELLER_017',
    SL_NULL_UPDATE: 'ERROR_SELLER_018',
    SL_NOT_FOUND: 'ERROR_SELLER_019'
    // ... autres codes d'erreur liés aux utilisateurs
};