module.exports = {
    DISHNAME_INVALID: 'ERROR_SELLER_023',
    DISHPRICE_INVALID: 'ERROR_SELLER_024',
    DISHDESC_INVALID: 'ERROR_SELLER_025',
    DISHIMG_INVALID: 'ERROR_SELLER_026',
    DISH_NOT_FOUND: 'ERROR_SELLER_027',
    IDDISH_NOT_FOUND: 'ERROR_SELLER_028'
    
    // ... autres codes d'erreur liés aux utilisateurs
};