module.exports = {
    CU_CREATED: 'SUCCESS_CUSTOMER_001',
    CU_UPDATED: 'SUCCESS_CUSTOMER_002',
    CU_DELETED: 'SUCCESS_CUSTOMER_003',
    CU_FETCHED: 'SUCCESS_CUSTOMER_004',
    CU_PASSWORD_RESET: 'SUCCESS_CUSTOMER_005',
    CU_LOGGED_IN: 'SUCCESS_CUSTOMER_006'
    // ... autres codes d'erreur liés aux utilisateurs
};